before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    binary: varnish-towncrier
    ldflags:
      - -s -w -X github.com/emgag/varnish-towncrier/internal/lib/version.Version={{.Version}} -X github.com/emgag/varnish-towncrier/internal/lib/version.Commit={{.Commit}} -X github.com/emgag/varnish-towncrier/internal/lib/version.Date={{.Date}}
    goos:
      - linux
    goarch:
      - amd64
archives:
  - files:
    - LICENSE
    - README.md
    - varnish-towncrier.yml.dist
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
